fixtures:
  repositories:
    firewall: 'https://github.com/autostructure/puppet-staging.git'
  forge_modules:
    stdlib:    'puppetlabs/stdlib'
    accounts:  'puppetlabs/accounts'
  symlinks:
    appinternals: "#{source_dir}"
