---
HOSTS:
  centos-6-x64:
    platform: el-6-x64
    image: centos:6.6
    hypervisor: docker
    pe_ver: '2016.4'
    roles:
      - agent

    # docker_image_commands:
       # - /sbin/sshd
       # - wget https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb
       # - sudo dpkg -i puppetlabs-release-pc1-trusty.deb
       # - sudo apt-get update -yq
       # - sudo apt-get -o Dpkg::Options::="--force-confold" install -yq puppet-agent=1.5.2-1trusty
       # - sudo apt-get -o Dpkg::Options::="--force-confold" install -yq puppet-agent=1.5.2-1trusty
CONFIG:
  log_level: verbose
  type: foss
ssh:
  password: root
  auth_methods: ["password"]
