---
HOSTS:
  centos6-64:
    roles:
     - agent
    platform: el-6-x86_64
    image: centos:6.6
    hypervisor: docker
    # docker_image_commands:
       # - /sbin/sshd
       # - wget https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb
       # - sudo dpkg -i puppetlabs-release-pc1-trusty.deb
       # - sudo apt-get update -yq
       # - sudo apt-get -o Dpkg::Options::="--force-confold" install -yq puppet-agent=1.5.2-1trusty
       # - sudo apt-get -o Dpkg::Options::="--force-confold" install -yq puppet-agent=1.5.2-1trusty
CONFIG:
  log_level: verbose
  type: foss
ssh:
  password: root
  auth_methods: ["password"]
