---
HOSTS:
  centos-7-x64:
    platform: centos-7-x64
    # box_url: https://vagrantcloud.com/puppetlabs/boxes/ubuntu-14.04-64-nocm
    box: centos/7
    hypervisor: vagrant
    roles:
      - agent
CONFIG:
  log_level: verbose
  type: foss
ssh:
  password: root
  auth_methods: ["password"]
